# Generated by Django 5.1.4 on 2025-01-28 11:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management_system', '0004_course_description_lesson_links_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='created_date',
            field=models.DateField(default=datetime.date(2025, 1, 28)),
        ),
        migrations.AlterField(
            model_name='user',
            name='joined_date',
            field=models.DateField(default=datetime.date(2025, 8, 28)),
        ),
    ]
