# Generated by Django 5.1.4 on 2025-01-28 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management_system', '0005_alter_lesson_created_date_alter_user_joined_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='instructor',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
