# Generated by Django 5.1.4 on 2025-01-29 10:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management_system', '0006_course_instructor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='created_date',
            field=models.DateField(default=datetime.date(2025, 1, 29)),
        ),
        migrations.AlterField(
            model_name='role',
            name='role',
            field=models.CharField(choices=[('admin', 'مدير'), ('teacher', 'مصحح'), ('junior', 'سنه اولي'), ('senior', 'سنه تانيه')], max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='joined_date',
            field=models.DateField(default=datetime.date(2025, 8, 29)),
        ),
    ]
