# Generated by Django 5.1.4 on 2025-02-03 13:48

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management_system', '0007_alter_lesson_created_date_alter_role_role_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('correct_answer', models.CharField(max_length=255)),
                ('question_type', models.CharField(max_length=512)),
                ('choices', models.TextField()),
                ('grade', models.PositiveSmallIntegerField(default=1)),
                ('auto_grade', models.BooleanField(default=True)),
            ],
        ),
        migrations.AlterField(
            model_name='lesson',
            name='created_date',
            field=models.DateField(default=datetime.date(2025, 2, 3)),
        ),
        migrations.AlterField(
            model_name='user',
            name='joined_date',
            field=models.DateField(default=datetime.date(2024, 8, 3)),
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('total_grade', models.PositiveSmallIntegerField(default=50)),
                ('opening_date', models.DateTimeField(default=datetime.datetime(2025, 2, 3, 15, 48, 15, 295913))),
                ('created_date', models.DateField(auto_now=True)),
                ('course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quiz', to='management_system.course')),
            ],
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.PositiveSmallIntegerField()),
                ('question', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_answers', to='management_system.question')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='grades', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
