# Generated by Django 5.1.4 on 2025-02-04 14:19

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management_system', '0008_question_alter_lesson_created_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='quiz',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='management_system.quiz'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quiz',
            name='closing_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 4, 16, 19, 24, 685085)),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='created_date',
            field=models.DateField(default=datetime.date(2025, 2, 4)),
        ),
        migrations.AlterField(
            model_name='question',
            name='choices',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='opening_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 4, 16, 19, 24, 685085)),
        ),
        migrations.AlterField(
            model_name='user',
            name='joined_date',
            field=models.DateField(default=datetime.date(2024, 8, 4)),
        ),
    ]
