# Generated by Django 5.1.4 on 2025-02-05 09:18

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management_system', '0009_question_quiz_quiz_closing_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='created_date',
            field=models.DateField(default=datetime.date(2025, 2, 5)),
        ),
        migrations.AlterField(
            model_name='question',
            name='correct_answer',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('mcq', 'اختيار من متعدد'), ('written', 'مقالي'), ('complete', 'اكمل')], max_length=512),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='closing_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 5, 11, 18, 28, 257832)),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quizzes', to='management_system.course'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='opening_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 5, 11, 18, 28, 257832)),
        ),
        migrations.AlterField(
            model_name='user',
            name='joined_date',
            field=models.DateField(default=datetime.date(2024, 8, 5)),
        ),
    ]
