# Generated by Django 5.1.4 on 2025-02-08 19:46

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management_system', '0010_alter_lesson_created_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='is_graded',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='submission',
            name='submitted_answer',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='lesson',
            name='created_date',
            field=models.DateField(default=datetime.date(2025, 2, 8)),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='closing_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 8, 21, 46, 43, 542012)),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='opening_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 8, 21, 46, 43, 542012)),
        ),
        migrations.AlterField(
            model_name='submission',
            name='grade',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='joined_date',
            field=models.DateField(default=datetime.date(2024, 8, 8)),
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_grade', models.PositiveSmallIntegerField()),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management_system.quiz')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'quiz')},
            },
        ),
    ]
