# Generated by Django 5.1.4 on 2025-02-17 18:18

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management_system', '0011_submission_is_graded_submission_submitted_answer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='created_date',
            field=models.DateField(default=datetime.date(2025, 2, 17)),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='closing_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 17, 18, 18, 32, 76755, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='opening_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 17, 18, 18, 32, 75262, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='submission',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user',
            name='joined_date',
            field=models.DateField(default=datetime.date(2024, 8, 17)),
        ),
    ]
