# Generated by Django 5.1.4 on 2025-07-30 07:29

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management_system', '0012_alter_lesson_created_date_alter_quiz_closing_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grade',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grade', to='management_system.quiz'),
        ),
        migrations.AlterField(
            model_name='grade',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submitted_quizzes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='created_date',
            field=models.DateField(default=datetime.date(2025, 7, 30)),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('mcq', 'Multiple Choice'), ('written', 'Written'), ('complete', 'Complete')], max_length=512),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='closing_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 7, 30, 7, 29, 42, 142352, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='opening_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 7, 30, 7, 29, 42, 142341, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='role',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('teacher', 'Teacher'), ('junior', 'First Year'), ('senior', 'Second Year')], max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='joined_date',
            field=models.DateField(default=datetime.date(2024, 8, 30)),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to='management_system.role'),
        ),
    ]
