# Generated by Django 5.1.4 on 2025-07-30 07:31

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management_system', '0013_alter_grade_quiz_alter_grade_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='closing_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 7, 30, 7, 31, 15, 213332, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='opening_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 7, 30, 7, 31, 15, 213323, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='management_system.role'),
        ),
    ]
