# Generated by Django 5.1.4 on 2026-03-22 08:08

import datetime
import management_system.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "management_system",
            "0014_alter_quiz_closing_date_alter_quiz_opening_date_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="lesson",
            name="created_date",
            field=models.DateField(default=datetime.date(2026, 3, 22)),
        ),
        migrations.AlterField(
            model_name="quiz",
            name="closing_date",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2026, 3, 22, 8, 8, 11, 405924, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="quiz",
            name="opening_date",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2026, 3, 22, 8, 8, 11, 405924, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="joined_date",
            field=models.DateField(
                default=management_system.models.assign_academic_date
            ),
        ),
    ]
