# Generated by Copilot on 2026-05-02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management_system', '0015_alter_lesson_created_date_alter_quiz_closing_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='config',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('mcq', 'Multiple Choice'), ('written', 'Written'), ('complete', 'Complete'), ('order_events', 'Order Events'), ('match_related', 'Match Related')], max_length=64),
        ),
    ]
