# Generated by Django 5.1.4 on 2026-06-11 11:57

import datetime
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("management_system", "0016_question_config"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lesson",
            name="created_date",
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name="quiz",
            name="closing_date",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="quiz",
            name="opening_date",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
