# Generated by Django 5.1.4 on 2026-07-14 19:48

import django.db.models.deletion
import management_system.models
from django.conf import settings
from django.db import migrations, models


def publish_existing_content(apps, schema_editor):
    apps.get_model("management_system", "Lesson").objects.update(status="published")
    apps.get_model("management_system", "Quiz").objects.update(status="published")


class Migration(migrations.Migration):
    dependencies = [
        ("management_system", "0018_align_question_type_choices"),
    ]

    operations = [
        migrations.CreateModel(
            name="MigrationReviewItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("item_type", models.CharField(max_length=50)),
                ("object_id", models.PositiveBigIntegerField(blank=True, null=True)),
                ("message", models.TextField()),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("info", "Info"),
                            ("warning", "Warning"),
                            ("error", "Error"),
                        ],
                        default="info",
                        max_length=20,
                    ),
                ),
                ("resolved", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="lesson",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("published", "Published"),
                    ("archived", "Archived"),
                ],
                default="draft",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="quiz",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("published", "Published"),
                    ("archived", "Archived"),
                ],
                default="draft",
                max_length=20,
            ),
        ),
        migrations.RunPython(
            publish_existing_content,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.CreateModel(
            name="AcademicYear",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=20)),
                ("level", models.PositiveIntegerField()),
                ("starts_on", models.DateField()),
                ("ends_on", models.DateField()),
                ("is_current", models.BooleanField(default=False)),
                (
                    "meeting_weekdays",
                    models.JSONField(
                        default=management_system.models.default_meeting_weekdays
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-starts_on", "level"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("level", "name"), name="academic_year_unique_level_name"
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("is_current", True)),
                        fields=("level",),
                        name="academic_year_one_current_per_level",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("ends_on__gt", models.F("starts_on"))),
                        name="academic_year_ends_after_starts",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="CourseOffering",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("instructor", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("published", "Published"),
                            ("archived", "Archived"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "academic_year",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="course_offerings",
                        to="management_system.academicyear",
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="offerings",
                        to="management_system.course",
                    ),
                ),
            ],
            options={
                "ordering": ["-academic_year__starts_on", "course__name"],
            },
        ),
        migrations.AddField(
            model_name="lesson",
            name="course_offering",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="lessons",
                to="management_system.courseoffering",
            ),
        ),
        migrations.AddField(
            model_name="quiz",
            name="course_offering",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="quizzes",
                to="management_system.courseoffering",
            ),
        ),
        migrations.CreateModel(
            name="Enrollment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "enrollment_type",
                    models.CharField(
                        choices=[
                            ("normal", "Normal"),
                            ("repeat", "Repeat"),
                            ("remedial", "Remedial"),
                            ("manual", "Manual"),
                        ],
                        default="normal",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("inactive", "Inactive"),
                            ("completed", "Completed"),
                            ("withdrawn", "Withdrawn"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("enrolled_at", models.DateTimeField(auto_now_add=True)),
                (
                    "academic_year",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="enrollments",
                        to="management_system.academicyear",
                    ),
                ),
                (
                    "course_offering",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="enrollments",
                        to="management_system.courseoffering",
                    ),
                ),
                (
                    "enrolled_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="created_enrollments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="enrollments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-enrolled_at"],
            },
        ),
        migrations.AddConstraint(
            model_name="courseoffering",
            constraint=models.UniqueConstraint(
                fields=("course", "academic_year"),
                name="course_offering_unique_course_year",
            ),
        ),
        migrations.AddConstraint(
            model_name="enrollment",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("course_offering__isnull", True), ("enrollment_type", "normal")
                    ),
                    models.Q(
                        ("course_offering__isnull", False),
                        ("enrollment_type__in", ["repeat", "remedial", "manual"]),
                    ),
                    _connector="OR",
                ),
                name="enrollment_target_matches_type",
            ),
        ),
        migrations.AddConstraint(
            model_name="enrollment",
            constraint=models.UniqueConstraint(
                condition=models.Q(("course_offering__isnull", True)),
                fields=("student", "academic_year"),
                name="enrollment_unique_full_year",
            ),
        ),
        migrations.AddConstraint(
            model_name="enrollment",
            constraint=models.UniqueConstraint(
                condition=models.Q(("course_offering__isnull", False)),
                fields=("student", "course_offering"),
                name="enrollment_unique_course_offering",
            ),
        ),
    ]
