# Generated by Django 5.1.4 on 2026-07-14 20:06

from django.db import migrations, models


def migrate_roles(apps, schema_editor):
    Role = apps.get_model("management_system", "Role")
    User = apps.get_model("management_system", "User")
    Enrollment = apps.get_model("management_system", "Enrollment")
    MigrationReviewItem = apps.get_model("management_system", "MigrationReviewItem")

    for role_name in ("staff", "moderator", "student"):
        Role.objects.get_or_create(role=role_name)

    try:
        teacher_role = Role.objects.get(role="teacher")
        moderator_role = Role.objects.get(role="moderator")
        User.objects.filter(role=teacher_role).update(role=moderator_role)
    except Role.DoesNotExist:
        pass

    for old_role_name, _new_level in [("junior", 1), ("senior", 2)]:
        try:
            old_role = Role.objects.get(role=old_role_name)
            student_role = Role.objects.get(role="student")
        except Role.DoesNotExist:
            continue

        for user in User.objects.filter(role=old_role):
            has_enrollment = Enrollment.objects.filter(
                student=user, status="active",
            ).exists()
            if has_enrollment:
                user.role = student_role
                user.save(update_fields=["role"])
            else:
                MigrationReviewItem.objects.create(
                    item_type="user",
                    object_id=user.pk,
                    message=f'User "{user.username}" has role "{old_role_name}" but no active Enrollment.',
                    severity="warning",
                )


def reverse_roles(apps, schema_editor):
    Role = apps.get_model("management_system", "Role")
    User = apps.get_model("management_system", "User")
    MigrationReviewItem = apps.get_model("management_system", "MigrationReviewItem")

    try:
        moderator_role = Role.objects.get(role="moderator")
        teacher_role = Role.objects.get(role="teacher")
        User.objects.filter(role=moderator_role).update(role=teacher_role)
    except Role.DoesNotExist:
        pass

    try:
        student_role = Role.objects.get(role="student")
        junior_role = Role.objects.get(role="junior")
        senior_role = Role.objects.get(role="senior")
        User.objects.filter(role=student_role).update(role=junior_role)
    except Role.DoesNotExist:
        pass

    MigrationReviewItem.objects.filter(
        item_type="user", message__contains="no active Enrollment",
    ).delete()

    for role_name in ("staff", "moderator", "student"):
        try:
            Role.objects.get(role=role_name).delete()
        except Role.DoesNotExist:
            pass


class Migration(migrations.Migration):
    dependencies = [
        ("management_system", "0020_backfill_academic_data"),
    ]

    operations = [
        migrations.AlterField(
            model_name="role",
            name="role",
            field=models.CharField(
                choices=[
                    ("admin", "Admin"),
                    ("staff", "Staff"),
                    ("moderator", "Moderator"),
                    ("student", "Student"),
                ],
                max_length=20,
                unique=True,
            ),
        ),
        migrations.RunPython(migrate_roles, reverse_code=reverse_roles),
    ]
