# Generated by Django 5.1.4 on 2026-07-14 21:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("management_system", "0025_attendance_models"),
    ]

    operations = [
        migrations.CreateModel(
            name="ViewingSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("part_id", models.CharField(max_length=100)),
                ("session_id", models.CharField(max_length=64, unique=True)),
                ("expires_at", models.DateTimeField()),
                ("last_heartbeat", models.DateTimeField(auto_now=True)),
                (
                    "lesson",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="viewing_sessions",
                        to="management_system.lesson",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="viewing_sessions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="VerifiedSegmentRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("segment_key", models.CharField(max_length=500)),
                ("requested_at", models.DateTimeField(auto_now_add=True)),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="verified_requests",
                        to="management_system.viewingsession",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="LectureProgress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("part_id", models.CharField(max_length=100)),
                ("merged_ranges", models.JSONField(default=list)),
                ("unique_seconds", models.PositiveIntegerField(default=0)),
                ("percent", models.PositiveSmallIntegerField(default=0)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "lesson",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lecture_progress",
                        to="management_system.lesson",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lecture_progress",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("student", "lesson", "part_id")},
            },
        ),
        migrations.AddIndex(
            model_name="viewingsession",
            index=models.Index(
                fields=["session_id"], name="management__session_810bcf_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="verifiedsegmentrequest",
            unique_together={("session", "segment_key")},
        ),
    ]
