# Generated by Django 5.1.4 on 2026-07-15 08:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("management_system", "0027_add_part_ids"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="identity_number",
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
