# Generated by Django 5.1.4 on 2026-07-15 18:36

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("management_system", "0028_alter_user_identity_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="verifiedsegmentrequest",
            name="expires_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="verifiedsegmentrequest",
            name="signature",
            field=models.CharField(blank=True, default="", max_length=128),
        ),
        migrations.AlterField(
            model_name="viewingsession",
            name="last_heartbeat",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
