# Generated by Django 5.1.4 on 2026-07-23 18:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("management_system", "0029_verifiedsegmentrequest_expires_at_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="academicyear",
            options={"ordering": ["-starts_on"]},
        ),
        migrations.RemoveConstraint(
            model_name="academicyear",
            name="academic_year_unique_level_name",
        ),
        migrations.RemoveConstraint(
            model_name="academicyear",
            name="academic_year_one_current_per_level",
        ),
        migrations.RemoveField(
            model_name="academicyear",
            name="level",
        ),
        migrations.AddField(
            model_name="enrollment",
            name="level",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="Academic Level"
            ),
        ),
    ]
