# Generated by Django 5.1.4 on 2026-07-23 19:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("management_system", "0030_alter_academicyear_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="academicyear",
            options={"ordering": ["-starts_on", "level"]},
        ),
        migrations.AddField(
            model_name="academicyear",
            name="level",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddConstraint(
            model_name="academicyear",
            constraint=models.UniqueConstraint(
                fields=("level", "name"), name="academic_year_unique_level_name"
            ),
        ),
        migrations.AddConstraint(
            model_name="academicyear",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_current", True)),
                fields=("level",),
                name="academic_year_one_current_per_level",
            ),
        ),
    ]
