# Generated by Django 5.1.4 on 2026-07-28 09:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "management_system",
            "0031_alter_academicyear_options_academicyear_level_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="LevelName",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("level", models.PositiveIntegerField(unique=True)),
                ("name_en", models.CharField(blank=True, default="", max_length=255)),
                ("name_ar", models.CharField(blank=True, default="", max_length=255)),
            ],
        ),
    ]
