# Generated by Django 5.1.4 on 2026-07-28 19:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("management_system", "0032_levelname"),
    ]

    operations = [
        migrations.CreateModel(
            name="Level",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ordering", models.PositiveIntegerField(unique=True)),
                ("name_en", models.CharField(blank=True, default="", max_length=255)),
                ("name_ar", models.CharField(blank=True, default="", max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Level",
                "verbose_name_plural": "Levels",
                "ordering": ["ordering"],
            },
        ),
    ]
