# Generated by Django 5.1.4 on 2026-07-28 19:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("management_system", "0033_level"),
    ]

    operations = [
        migrations.AddField(
            model_name="academicyear",
            name="level_ref",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="academic_years",
                to="management_system.level",
            ),
        ),
        migrations.AddField(
            model_name="course",
            name="level_ref",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="courses",
                to="management_system.level",
            ),
        ),
    ]
