# Generated by Django 5.1.4 on 2026-08-02 07:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("management_system", "0046_enrollment_scope_filter_index"),
    ]

    operations = [
        migrations.AddField(
            model_name="academicyearlevel",
            name="meeting_names",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
