# Generated by Django 5.1.4 on 2026-08-02

from django.db import migrations, models
import django.db.models.deletion


def reject_legacy_meeting_names(apps, schema_editor):
    AcademicYearLevel = apps.get_model("management_system", "AcademicYearLevel")
    if AcademicYearLevel.objects.exclude(meeting_names={}).exists():
        raise RuntimeError(
            "Cannot replace free-text meeting names: one or more AcademicYearLevel rows contain values. "
            "Export and map those values to course offerings before applying 0048."
        )


class Migration(migrations.Migration):
    dependencies = [
        ("management_system", "0047_academic_year_level_meeting_names"),
    ]

    operations = [
        migrations.RunPython(reject_legacy_meeting_names, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name="academicyearlevel",
            name="meeting_names",
        ),
        migrations.CreateModel(
            name="AcademicYearLevelMeeting",
            fields=[
                (
                    "id",
                    models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID"),
                ),
                ("weekday", models.PositiveSmallIntegerField()),
                (
                    "academic_year_level",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="calendar_meetings",
                        to="management_system.academicyearlevel",
                    ),
                ),
                (
                    "course_offering",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="calendar_meetings",
                        to="management_system.courseoffering",
                    ),
                ),
            ],
            options={
                "ordering": ["academic_year_level__level__ordering", "weekday"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("academic_year_level", "weekday"),
                        name="academic_scope_meeting_weekday_unique",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(weekday__gte=0, weekday__lte=6),
                        name="academic_scope_meeting_weekday_valid",
                    ),
                ],
            },
        ),
    ]
