# Generated by Django 5.1.4 on 2026-08-02

from django.db import migrations, models


def reject_weekday_meetings(apps, schema_editor):
    Meeting = apps.get_model("management_system", "AcademicYearLevelMeeting")
    if Meeting.objects.exists():
        raise RuntimeError(
            "Cannot convert recurring weekday meetings to date-specific meetings automatically. "
            "Remove or explicitly migrate existing AcademicYearLevelMeeting rows before applying 0049."
        )


class Migration(migrations.Migration):
    dependencies = [
        ("management_system", "0048_academic_year_level_meetings"),
    ]

    operations = [
        migrations.RunPython(reject_weekday_meetings, migrations.RunPython.noop),
        migrations.RemoveConstraint(
            model_name="academicyearlevelmeeting",
            name="academic_scope_meeting_weekday_unique",
        ),
        migrations.RemoveConstraint(
            model_name="academicyearlevelmeeting",
            name="academic_scope_meeting_weekday_valid",
        ),
        migrations.RemoveField(
            model_name="academicyearlevelmeeting",
            name="weekday",
        ),
        migrations.AddField(
            model_name="academicyearlevelmeeting",
            name="meeting_date",
            field=models.DateField(),
        ),
        migrations.AddConstraint(
            model_name="academicyearlevelmeeting",
            constraint=models.UniqueConstraint(
                fields=("academic_year_level", "meeting_date"),
                name="academic_scope_meeting_date_unique",
            ),
        ),
        migrations.AlterModelOptions(
            name="academicyearlevelmeeting",
            options={"ordering": ["meeting_date", "academic_year_level__level__ordering"]},
        ),
    ]
