# Generated by Django 5.1.4 on 2026-08-07 12:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("management_system", "0054_telegram_accounts_and_webhook_updates"),
    ]

    operations = [
        migrations.CreateModel(
            name="TelegramNotificationDelivery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("idempotency_key", models.CharField(max_length=255, unique=True)),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("lesson_published", "Lesson published"),
                            ("quiz_opening", "Exam opening"),
                        ],
                        max_length=32,
                    ),
                ),
                ("scheduled_for", models.DateTimeField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("queued", "Queued"),
                            ("sending", "Sending"),
                            ("sent", "Sent"),
                            ("failed", "Failed"),
                            ("skipped", "Skipped"),
                        ],
                        default="queued",
                        max_length=16,
                    ),
                ),
                ("attempt_count", models.PositiveSmallIntegerField(default=0)),
                ("telegram_message_id", models.BigIntegerField(blank=True, null=True)),
                (
                    "last_error",
                    models.CharField(blank=True, default="", max_length=500),
                ),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "lesson",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="telegram_notification_deliveries",
                        to="management_system.lesson",
                    ),
                ),
                (
                    "quiz",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="telegram_notification_deliveries",
                        to="management_system.quiz",
                    ),
                ),
                (
                    "telegram_account",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="notification_deliveries",
                        to="management_system.telegramaccount",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="telegram_notification_deliveries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["status", "scheduled_for"], name="tg_delivery_due_idx"
                    ),
                    models.Index(
                        fields=["user", "status"], name="tg_delivery_user_status_idx"
                    ),
                    models.Index(
                        fields=["notification_type", "lesson"],
                        name="tg_delivery_lesson_idx",
                    ),
                    models.Index(
                        fields=["notification_type", "quiz"],
                        name="tg_delivery_quiz_idx",
                    ),
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ("lesson__isnull", False),
                                ("notification_type", "lesson_published"),
                                ("quiz__isnull", True),
                            ),
                            models.Q(
                                ("lesson__isnull", True),
                                ("notification_type", "quiz_opening"),
                                ("quiz__isnull", False),
                            ),
                            _connector="OR",
                        ),
                        name="telegram_delivery_source_matches_type",
                    )
                ],
            },
        ),
    ]
