# Generated by Django 5.1.4 on 2026-08-07 13:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("management_system", "0055_telegramnotificationdelivery"),
    ]

    operations = [
        migrations.CreateModel(
            name="TelegramConversation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Open"),
                            ("claimed", "Claimed"),
                            ("handled", "Handled"),
                            ("blocked", "Blocked"),
                        ],
                        default="open",
                        max_length=16,
                    ),
                ),
                ("claimed_at", models.DateTimeField(blank=True, null=True)),
                ("handled_at", models.DateTimeField(blank=True, null=True)),
                ("last_message_at", models.DateTimeField(blank=True, null=True)),
                ("version", models.PositiveIntegerField(default=1)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "claimed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="claimed_telegram_conversations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="telegram_conversations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TelegramMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "direction",
                    models.CharField(
                        choices=[("inbound", "Inbound"), ("outbound", "Outbound")],
                        max_length=16,
                    ),
                ),
                ("telegram_chat_id", models.BigIntegerField(blank=True, null=True)),
                ("telegram_message_id", models.BigIntegerField(blank=True, null=True)),
                ("telegram_update_id", models.BigIntegerField(blank=True, null=True)),
                (
                    "reply_to_telegram_message_id",
                    models.BigIntegerField(blank=True, null=True),
                ),
                (
                    "content_type",
                    models.CharField(
                        choices=[
                            ("text", "Text"),
                            ("photo", "Photo"),
                            ("document", "Document"),
                            ("video", "Video"),
                            ("digest", "Digest"),
                            ("unsupported", "Unsupported"),
                        ],
                        max_length=16,
                    ),
                ),
                ("text", models.TextField(blank=True, default="")),
                (
                    "delivery_status",
                    models.CharField(
                        choices=[
                            ("received", "Received"),
                            ("queued", "Queued"),
                            ("sent", "Sent"),
                            ("failed", "Failed"),
                        ],
                        default="received",
                        max_length=16,
                    ),
                ),
                (
                    "delivery_error",
                    models.CharField(blank=True, default="", max_length=500),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                (
                    "conversation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="management_system.telegramconversation",
                    ),
                ),
                (
                    "sender_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="telegram_messages",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TelegramAttachment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("telegram_file_id", models.CharField(max_length=255)),
                ("media_type", models.CharField(max_length=16)),
                ("r2_key", models.CharField(blank=True, default="", max_length=1024)),
                (
                    "original_name",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("mime_type", models.CharField(blank=True, default="", max_length=255)),
                ("size_bytes", models.PositiveBigIntegerField(default=0)),
                ("sha256", models.CharField(blank=True, default="", max_length=64)),
                ("is_available", models.BooleanField(default=False)),
                ("error", models.CharField(blank=True, default="", max_length=500)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "message",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attachments",
                        to="management_system.telegrammessage",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="telegramconversation",
            index=models.Index(
                fields=["status", "last_message_at"], name="tg_conversation_status_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="telegramconversation",
            index=models.Index(
                fields=["user", "status"], name="tg_conversation_user_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="telegramconversation",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status__in", ["open", "claimed"])),
                fields=("user",),
                name="telegram_one_active_conversation",
            ),
        ),
        migrations.AddIndex(
            model_name="telegrammessage",
            index=models.Index(
                fields=["conversation", "created_at"],
                name="tg_message_conversation_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="telegrammessage",
            index=models.Index(
                fields=["delivery_status", "created_at"], name="tg_message_delivery_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="telegrammessage",
            constraint=models.UniqueConstraint(
                condition=models.Q(("telegram_update_id__isnull", False)),
                fields=("telegram_update_id",),
                name="telegram_message_update_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="telegrammessage",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("telegram_chat_id__isnull", False),
                    ("telegram_message_id__isnull", False),
                ),
                fields=("telegram_chat_id", "telegram_message_id"),
                name="telegram_message_chat_id_unique",
            ),
        ),
        migrations.AddIndex(
            model_name="telegramattachment",
            index=models.Index(
                fields=["media_type", "is_available"], name="tg_attachment_media_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="telegramattachment",
            constraint=models.UniqueConstraint(
                fields=("message", "telegram_file_id"),
                name="telegram_attachment_file_unique",
            ),
        ),
    ]
