# Generated by Django 5.1

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("management_system", "0056_telegramconversation_telegrammessage_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="TelegramBroadcast",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("message", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("queued", "Queued"),
                            ("sending", "Sending"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="draft",
                        max_length=16,
                    ),
                ),
                ("confirmed_at", models.DateTimeField(blank=True, null=True)),
                ("queued_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("recipient_count", models.PositiveIntegerField(default=0)),
                ("sent_count", models.PositiveIntegerField(default=0)),
                ("failed_count", models.PositiveIntegerField(default=0)),
                ("last_error", models.CharField(blank=True, default="", max_length=500)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "academic_year",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="telegram_broadcasts",
                        to="management_system.academicyear",
                    ),
                ),
                (
                    "confirmed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="confirmed_telegram_broadcasts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="created_telegram_broadcasts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "level",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="telegram_broadcasts",
                        to="management_system.level",
                    ),
                ),
            ],
            options={"ordering": ["-created_at", "-pk"]},
        ),
        migrations.CreateModel(
            name="TelegramBroadcastAttachment",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("r2_key", models.CharField(max_length=1024)),
                ("original_name", models.CharField(max_length=255)),
                ("mime_type", models.CharField(blank=True, default="", max_length=255)),
                ("size_bytes", models.PositiveBigIntegerField(default=0)),
                ("sha256", models.CharField(blank=True, default="", max_length=64)),
                ("is_available", models.BooleanField(default=False)),
                ("error", models.CharField(blank=True, default="", max_length=500)),
                ("ordering", models.PositiveSmallIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "broadcast",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attachments",
                        to="management_system.telegrambroadcast",
                    ),
                ),
            ],
            options={"ordering": ["ordering", "pk"]},
        ),
        migrations.CreateModel(
            name="TelegramBroadcastRecipient",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("queued", "Queued"),
                            ("sending", "Sending"),
                            ("sent", "Sent"),
                            ("failed", "Failed"),
                            ("skipped", "Skipped"),
                        ],
                        default="queued",
                        max_length=16,
                    ),
                ),
                ("telegram_chat_id", models.BigIntegerField()),
                ("user_username", models.CharField(blank=True, default="", max_length=150)),
                ("user_display_name", models.CharField(blank=True, default="", max_length=255)),
                ("attempt_count", models.PositiveSmallIntegerField(default=0)),
                ("telegram_message_id", models.BigIntegerField(blank=True, null=True)),
                ("scheduled_for", models.DateTimeField()),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                ("last_error", models.CharField(blank=True, default="", max_length=500)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "broadcast",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recipients",
                        to="management_system.telegrambroadcast",
                    ),
                ),
                (
                    "telegram_account",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="broadcast_recipients",
                        to="management_system.telegramaccount",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="telegram_broadcast_recipients",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={"ordering": ["pk"]},
        ),
        migrations.AddIndex(
            model_name="telegrambroadcast",
            index=models.Index(fields=["status", "created_at"], name="tg_broadcast_status_idx"),
        ),
        migrations.AddIndex(
            model_name="telegrambroadcast",
            index=models.Index(fields=["academic_year", "level"], name="tg_broadcast_target_idx"),
        ),
        migrations.AddConstraint(
            model_name="telegrambroadcast",
            constraint=models.CheckConstraint(
                condition=models.Q(("message", ""), _negated=True),
                name="tg_broadcast_message_not_empty",
            ),
        ),
        migrations.AddConstraint(
            model_name="telegrambroadcastattachment",
            constraint=models.UniqueConstraint(
                fields=("broadcast", "r2_key"), name="tg_broadcast_attachment_key_unique"
            ),
        ),
        migrations.AddIndex(
            model_name="telegrambroadcastrecipient",
            index=models.Index(
                fields=["broadcast", "status", "scheduled_for"], name="tg_broadcast_due_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="telegrambroadcastrecipient",
            index=models.Index(
                fields=["broadcast", "status"], name="tg_bcast_recipient_status_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="telegrambroadcastrecipient",
            constraint=models.UniqueConstraint(
                fields=("broadcast", "user"), name="tg_broadcast_recipient_user_unique"
            ),
        ),
    ]
