# Generated by Django 5.1.4 on 2026-08-14 14:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("management_system", "0059_promotion_history_method_reason"),
    ]

    operations = [
        migrations.CreateModel(
            name="MediaProcessingJob",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("public_id", models.UUIDField(editable=False, unique=True)),
                ("requested_folder", models.CharField(max_length=1024)),
                ("original_filename", models.CharField(max_length=255)),
                ("output_base_name", models.CharField(max_length=255)),
                ("source_kind", models.CharField(max_length=16)),
                ("source_key", models.CharField(max_length=1024, unique=True)),
                ("source_size", models.PositiveBigIntegerField()),
                (
                    "source_etag",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "source_sha256",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                ("part_id", models.CharField(blank=True, default="", max_length=100)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("awaiting_upload", "Awaiting upload"),
                            ("queued", "Queued"),
                            ("processing", "Processing"),
                            ("uploading", "Uploading"),
                            ("verifying", "Verifying"),
                            ("succeeded", "Succeeded"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="awaiting_upload",
                        max_length=24,
                    ),
                ),
                (
                    "phase",
                    models.CharField(
                        choices=[
                            ("upload", "Upload"),
                            ("queued", "Queued"),
                            ("download", "Downloading source"),
                            ("probe", "Inspecting source"),
                            ("encode", "Processing media"),
                            ("upload_output", "Uploading output"),
                            ("verify", "Verifying output"),
                            ("attach", "Attaching to lesson"),
                            ("complete", "Complete"),
                            ("failed", "Failed"),
                        ],
                        default="upload",
                        max_length=24,
                    ),
                ),
                ("progress", models.PositiveSmallIntegerField(default=0)),
                ("attempt_count", models.PositiveIntegerField(default=0)),
                ("error_code", models.CharField(blank=True, default="", max_length=80)),
                ("error_message", models.TextField(blank=True, default="")),
                ("failure_history", models.JSONField(default=list)),
                ("output_keys", models.JSONField(default=list)),
                (
                    "manifest_key",
                    models.CharField(blank=True, default="", max_length=1024),
                ),
                (
                    "download_key",
                    models.CharField(blank=True, default="", max_length=1024),
                ),
                (
                    "attachment_status",
                    models.CharField(
                        choices=[
                            ("not_requested", "Not requested"),
                            ("pending", "Pending"),
                            ("attached", "Attached"),
                            ("failed", "Failed"),
                        ],
                        default="not_requested",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("source_acknowledged_at", models.DateTimeField(blank=True, null=True)),
                ("upload_ack_deadline_at", models.DateTimeField()),
                ("last_heartbeat_at", models.DateTimeField(blank=True, null=True)),
                ("last_dispatched_at", models.DateTimeField(blank=True, null=True)),
                ("staging_deleted_at", models.DateTimeField(blank=True, null=True)),
                ("staging_expires_at", models.DateTimeField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="media_processing_jobs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "lesson",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="media_processing_jobs",
                        to="management_system.lesson",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-pk"],
                "indexes": [
                    models.Index(
                        fields=["status", "last_dispatched_at"],
                        name="media_job_status_dispatch_idx",
                    ),
                    models.Index(
                        fields=["status", "last_heartbeat_at"],
                        name="media_job_status_heartbeat_idx",
                    ),
                    models.Index(
                        fields=["status", "upload_ack_deadline_at"],
                        name="media_job_status_upload_idx",
                    ),
                    models.Index(
                        fields=["created_by", "created_at"],
                        name="media_job_creator_created_idx",
                    ),
                    models.Index(
                        fields=["lesson", "attachment_status"],
                        name="media_job_lesson_attach_idx",
                    ),
                ],
            },
        ),
    ]
