# Generated by Django 5.1.4 on 2026-09-02 21:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("management_system", "0072_mobile_viewing_session_binding"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={},
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(
                fields=["application_status", "-date_joined", "-id"],
                name="user_app_status_date_idx",
            ),
        ),
    ]
