# Generated by Django 5.1.4 on 2026-09-15 18:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("management_system", "0075_arabic_search_normalization"),
    ]

    operations = [
        migrations.AddField(
            model_name="telegramconversation",
            name="admin_read_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
