# Generated by Django 5.1.4 on 2026-09-15 19:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("management_system", "0076_telegram_conversation_admin_read"),
    ]

    operations = [
        migrations.AddField(
            model_name="telegrammessage",
            name="origin",
            field=models.CharField(
                blank=True,
                choices=[("telegram", "Via Telegram"), ("web", "Via Web")],
                default="",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="telegrammessage",
            name="resolution",
            field=models.CharField(
                blank=True,
                choices=[
                    ("deleted", "Deleted"),
                    ("edited", "Edited"),
                    ("failed", "Failed"),
                ],
                default="",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="telegrammessage",
            name="resolved_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="telegrammessage",
            name="source_message",
            field=models.ForeignKey(
                blank=True,
                help_text="For digest rows: the student message announced. For replies: the student message answered.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="linked_messages",
                to="management_system.telegrammessage",
            ),
        ),
    ]
