# Generated by Django 5.1.4 on 2026-09-16 19:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("management_system", "0077_telegram_message_resolution"),
    ]

    operations = [
        migrations.AddField(
            model_name="telegramaccount",
            name="phone",
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
