# Generated by Django 5.1.4 on 2026-09-17 07:04

from django.db import migrations, models


class Migration(migrations.Migration):
    """Keep delivery history when its lesson or quiz is deleted.

    ``lesson``/``quiz`` are ``SET_NULL`` so delivery/audit rows survive source
    deletion; the old check still required the matching source to stay non-null,
    which made every lesson/quiz delete fail with a constraint violation. The
    relaxed rule keeps source exclusivity (the other source must be NULL) and
    mirrors ``student_notification_source_type_match``.
    """

    dependencies = [
        ("management_system", "0078_telegram_account_phone"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="telegramnotificationdelivery",
            name="telegram_delivery_source_matches_type",
        ),
        migrations.AddConstraint(
            model_name="telegramnotificationdelivery",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("notification_type", "lesson_published"),
                        ("quiz__isnull", True),
                    ),
                    models.Q(
                        ("lesson__isnull", True), ("notification_type", "quiz_opening")
                    ),
                    _connector="OR",
                ),
                name="telegram_delivery_source_matches_type",
            ),
        ),
    ]
