# Generated by Django 5.1.4 on 2026-09-17 09:41

import django.db.models.deletion
import management_system.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("management_system", "0079_relax_telegram_delivery_source_constraint"),
    ]

    operations = [
        migrations.AddField(
            model_name="attendancerecord",
            name="source",
            field=models.CharField(
                choices=[
                    ("scan", "Scan"),
                    ("auto", "Auto reconciliation"),
                    ("manual", "Manual reconciliation"),
                ],
                default="scan",
                max_length=10,
            ),
        ),
        migrations.CreateModel(
            name="AttendancePolicy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "singleton",
                    models.CharField(
                        default="default", editable=False, max_length=20, unique=True
                    ),
                ),
                (
                    "entrance_deadline",
                    models.TimeField(
                        default=management_system.models.default_attendance_entrance_deadline
                    ),
                ),
                (
                    "exit_time",
                    models.TimeField(
                        default=management_system.models.default_attendance_exit_time
                    ),
                ),
                ("buffer_minutes", models.PositiveSmallIntegerField(default=5)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="attendance_policy_updates",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Attendance Policy",
                "verbose_name_plural": "Attendance Policies",
            },
        ),
    ]
