# Generated by Django 5.1.4 on 2026-09-17 13:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("management_system", "0080_attendance_policy_and_source"),
    ]

    operations = [
        migrations.CreateModel(
            name="Announcement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title_ar", models.CharField(max_length=255)),
                ("body_ar", models.TextField()),
                ("title_en", models.CharField(max_length=255)),
                ("body_en", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("queued", "Queued"),
                            ("sending", "Sending"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="queued",
                        max_length=16,
                    ),
                ),
                ("recipient_count", models.PositiveIntegerField(default=0)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "last_error",
                    models.CharField(blank=True, default="", max_length=500),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-created_at", "-pk"],
            },
        ),
        migrations.RemoveConstraint(
            model_name="studentnotification",
            name="student_notification_route_ids_positive",
        ),
        migrations.RemoveConstraint(
            model_name="studentnotification",
            name="student_notification_source_type_match",
        ),
        migrations.AlterField(
            model_name="studentnotification",
            name="navigation_type",
            field=models.CharField(
                choices=[("lesson", "Lesson"), ("quiz", "Exam"), ("none", "None")],
                max_length=16,
            ),
        ),
        migrations.AlterField(
            model_name="studentnotification",
            name="notification_type",
            field=models.CharField(
                choices=[
                    ("lesson_published", "Lesson published"),
                    ("quiz_opening", "Exam opening"),
                    ("announcement", "Announcement"),
                ],
                max_length=32,
            ),
        ),
        migrations.AddField(
            model_name="announcement",
            name="academic_year",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="announcements",
                to="management_system.academicyear",
            ),
        ),
        migrations.AddField(
            model_name="announcement",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_announcements",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="announcement",
            name="levels",
            field=models.ManyToManyField(
                blank=True,
                help_text="With no level selected the announcement targets every active student.",
                related_name="announcements",
                to="management_system.level",
            ),
        ),
        migrations.AddField(
            model_name="studentnotification",
            name="announcement",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="notifications",
                to="management_system.announcement",
            ),
        ),
        migrations.AddConstraint(
            model_name="studentnotification",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("effective_closing_at__isnull", True),
                        ("effective_opening_at__isnull", True),
                        ("navigation_type", "lesson"),
                        ("notification_type", "lesson_published"),
                        ("quiz__isnull", True),
                    ),
                    models.Q(
                        ("effective_closing_at__isnull", False),
                        ("effective_opening_at__isnull", False),
                        ("lesson__isnull", True),
                        ("navigation_type", "quiz"),
                        ("notification_type", "quiz_opening"),
                    ),
                    models.Q(
                        ("effective_closing_at__isnull", True),
                        ("effective_opening_at__isnull", True),
                        ("lesson__isnull", True),
                        ("navigation_type", "none"),
                        ("notification_type", "announcement"),
                        ("quiz__isnull", True),
                    ),
                    _connector="OR",
                ),
                name="student_notification_source_type_match",
            ),
        ),
        migrations.AddConstraint(
            model_name="studentnotification",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("entity_id__gt", 0), ("offering_id__gt", 0)),
                    models.Q(
                        ("entity_id", 0),
                        ("notification_type", "announcement"),
                        ("offering_id", 0),
                    ),
                    _connector="OR",
                ),
                name="student_notification_route_ids_positive",
            ),
        ),
        migrations.AddIndex(
            model_name="announcement",
            index=models.Index(
                fields=["-created_at", "-id"], name="announcement_recent_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="announcement",
            index=models.Index(
                fields=["status", "updated_at"], name="announcement_status_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="announcement",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("title_ar", ""), _negated=True),
                    models.Q(("body_ar", ""), _negated=True),
                    models.Q(("title_en", ""), _negated=True),
                    models.Q(("body_en", ""), _negated=True),
                ),
                name="announcement_content_not_empty",
            ),
        ),
    ]
