# Generated by Django 5.2.17 on 2026-10-01 08:11

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("management_system", "0089_canonical_usernames"),
    ]

    operations = [
        migrations.AddField(
            model_name="academicyear",
            name="graduation_level",
            field=models.ForeignKey(
                blank=True,
                help_text="The level whose completion opens the graduation gallery for this year.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="graduation_years",
                to="management_system.level",
            ),
        ),
        migrations.CreateModel(
            name="GraduationGalleryItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[("image", "Image"), ("video", "Video")], max_length=10
                    ),
                ),
                ("display_key", models.CharField(max_length=500, unique=True)),
                ("original_key", models.CharField(max_length=500, unique=True)),
                ("original_filename", models.CharField(max_length=255)),
                ("byte_size", models.PositiveBigIntegerField(default=0)),
                ("width", models.PositiveIntegerField(blank=True, null=True)),
                ("height", models.PositiveIntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "academic_year_level",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="gallery_items",
                        to="management_system.academicyearlevel",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="gallery_uploads",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-pk"],
                "indexes": [
                    models.Index(
                        fields=["academic_year_level", "-created_at", "-id"],
                        name="gallery_item_scope_created_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="GraduationGalleryJob",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "public_id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("staging_key", models.CharField(max_length=500)),
                ("original_filename", models.CharField(max_length=255)),
                (
                    "content_type",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                ("is_zip", models.BooleanField(default=False)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("queued", "Queued"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="queued",
                        max_length=20,
                    ),
                ),
                ("total_files", models.PositiveIntegerField(default=0)),
                ("processed_files", models.PositiveIntegerField(default=0)),
                ("failed_files", models.PositiveIntegerField(default=0)),
                ("last_error", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "academic_year_level",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="gallery_jobs",
                        to="management_system.academicyearlevel",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="gallery_jobs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-pk"],
                "indexes": [
                    models.Index(
                        fields=["status", "created_at"], name="gallery_job_status_idx"
                    )
                ],
            },
        ),
    ]
