# Generated by Django 5.2.17 on 2026-10-01 09:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("management_system", "0091_mobile_push_device_token_optional"),
    ]

    operations = [
        migrations.CreateModel(
            name="MobileAppRelease",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("version_name", models.CharField(max_length=50)),
                ("version_code", models.PositiveIntegerField(unique=True)),
                ("apk_key", models.CharField(max_length=500, unique=True)),
                ("file_size", models.PositiveBigIntegerField(default=0)),
                ("release_notes", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="app_releases",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-version_code", "-pk"],
            },
        ),
        migrations.CreateModel(
            name="StudentBanner",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("body", models.TextField()),
                (
                    "action_label",
                    models.CharField(blank=True, default="", max_length=80),
                ),
                (
                    "action_url",
                    models.CharField(blank=True, default="", max_length=2048),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at", "-pk"],
                "indexes": [
                    models.Index(
                        fields=["is_active", "-created_at"],
                        name="student_banner_active_idx",
                    )
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(("action_label", ""), ("action_url", "")),
                            models.Q(("action_label__gt", ""), ("action_url__gt", "")),
                            _connector="OR",
                        ),
                        name="student_banner_action_pair",
                    )
                ],
            },
        ),
    ]
