# Generated by Django 5.2.17 on 2026-10-06 17:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("management_system", "0095_media_job_stop_and_cleanup"),
    ]

    operations = [
        migrations.CreateModel(
            name="SignupSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "singleton",
                    models.CharField(
                        default="default", editable=False, max_length=20, unique=True
                    ),
                ),
                ("is_open", models.BooleanField(default=True)),
                ("title_en", models.CharField(blank=True, default="", max_length=200)),
                ("title_ar", models.CharField(blank=True, default="", max_length=200)),
                (
                    "subtitle_en",
                    models.CharField(blank=True, default="", max_length=500),
                ),
                (
                    "subtitle_ar",
                    models.CharField(blank=True, default="", max_length=500),
                ),
                (
                    "closed_title_en",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                (
                    "closed_title_ar",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                ("closed_message_en", models.TextField(blank=True, default="")),
                ("closed_message_ar", models.TextField(blank=True, default="")),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "intake_scope",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="signup_intake_settings",
                        to="management_system.academicyearlevel",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="signup_settings_updates",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Signup Settings",
                "verbose_name_plural": "Signup Settings",
            },
        ),
    ]
