"""
Django settings for learning_platform project.

Generated by 'django-admin startproject' using Django 5.1.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
from urllib.parse import urlsplit
import os
from dotenv import load_dotenv
from django.core.exceptions import ImproperlyConfigured
from django.urls import reverse_lazy
load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('DJANGO_SECRET_KEY')
if not SECRET_KEY:
    raise ImproperlyConfigured('DJANGO_SECRET_KEY environment variable is required')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DJANGO_DEBUG', '').lower() in ('true', '1', 'yes')
STATIC_ASSET_VERSION = os.getenv('STATIC_ASSET_VERSION', 'dev')

# Nginx terminates TLS and forwards the original protocol. Secure cookie
# defaults turn on automatically for production while remaining convenient for
# local HTTP development.
SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
SESSION_COOKIE_SECURE = os.getenv(
    "DJANGO_SESSION_COOKIE_SECURE", "False" if DEBUG else "True"
).lower() in ("true", "1", "yes")
CSRF_COOKIE_SECURE = os.getenv(
    "DJANGO_CSRF_COOKIE_SECURE", "False" if DEBUG else "True"
).lower() in ("true", "1", "yes")

def _env_csv(name, default=''):
    return [value.strip() for value in os.getenv(name, default).split(',') if value.strip()]


def _is_plain_domain(host):
    return (
        host
        and host != '*'
        and not host.startswith(('.', '*'))
        and '.' in host
        and not host.replace('.', '').isdigit()
        and ':' not in host
    )


ALLOWED_HOSTS = []
for configured_host in _env_csv('DJANGO_ALLOWED_HOSTS', '*'):
    configured_host = configured_host.strip()
    if configured_host.startswith('*.'):
        configured_host = f'.{configured_host[2:]}'
    if configured_host:
        ALLOWED_HOSTS.append(configured_host)
        if _is_plain_domain(configured_host):
            ALLOWED_HOSTS.append(f'.{configured_host}')
ALLOWED_HOSTS = list(dict.fromkeys(ALLOWED_HOSTS))

CSRF_TRUSTED_ORIGINS = []
for configured_origin in _env_csv('DJANGO_CSRF_TRUSTED_ORIGINS'):
    configured_origin = configured_origin.rstrip('/')
    if not configured_origin:
        continue
    CSRF_TRUSTED_ORIGINS.append(configured_origin)
    origin_parts = urlsplit(configured_origin)
    origin_host = origin_parts.hostname or ''
    if (
        origin_parts.scheme in ('http', 'https')
        and not origin_parts.port
        and not origin_parts.username
        and _is_plain_domain(origin_host)
    ):
        CSRF_TRUSTED_ORIGINS.append(f'{origin_parts.scheme}://*.{origin_host}')
CSRF_TRUSTED_ORIGINS = list(dict.fromkeys(CSRF_TRUSTED_ORIGINS))

TIME_ZONE = os.getenv('DJANGO_TIME_ZONE', 'Africa/Cairo')

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # Third Parties
    "django_extensions",
    'crispy_forms',
    'crispy_bootstrap5',
    # Applications
    'management_system'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    # ponytail: removed global COEP — breaks CDN resources; scoped to upload view via ffmpeg_headers
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.locale.LocaleMiddleware', # Add this for localization
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'management_system.middleware.SessionExpiryUpdate'
]

ROOT_URLCONF = 'learning_platform.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'django.template.context_processors.i18n',
                'management_system.context_processors.static_asset_version',
                'management_system.context_processors.localized_alternate_urls',
            ],
        },
    },
]

WSGI_APPLICATION = 'learning_platform.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.getenv('POSTGRES_DB', 'lms_database'),
        'USER': os.getenv('POSTGRES_USER', 'lms_user'),
        'PASSWORD': os.getenv('POSTGRES_PASSWORD', 'dev_password_change_me'),
        'HOST': os.getenv('POSTGRES_HOST', 'localhost'),
        'PORT': os.getenv('POSTGRES_PORT', '5432'),
    },
    'sqlite_source': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.getenv('SQLITE_SOURCE_PATH', str(BASE_DIR / 'db.sqlite3')),
    },
}

# Celery (Redis broker / result backend — defaults to the redis service on lms_network)
CELERY_BROKER_URL = os.getenv("CELERY_BROKER_URL") or os.getenv(
    "REDIS_URL", "redis://redis:6379/0"
)
CELERY_RESULT_BACKEND = os.getenv("CELERY_RESULT_BACKEND") or os.getenv(
    "REDIS_URL", "redis://redis:6379/0"
)
CELERY_TASK_TRACK_STARTED = True
CELERY_TIMEZONE = TIME_ZONE

# Keep Django's request ceiling aligned with the Nginx 2 GiB upload ceiling.
# Uploaded files above FILE_UPLOAD_MAX_MEMORY_SIZE are spooled to disk by
# Django's temporary-file upload handler rather than held in process memory.
DATA_UPLOAD_MAX_MEMORY_SIZE = int(
    os.getenv("DJANGO_DATA_UPLOAD_MAX_MEMORY_SIZE", str(2 * 1024 ** 3))
)
FILE_UPLOAD_MAX_MEMORY_SIZE = int(
    os.getenv("DJANGO_FILE_UPLOAD_MAX_MEMORY_SIZE", str(10 * 1024 ** 2))
)

# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en'
LANGUAGES = [
    ('en', 'English'),
    ('ar', 'Arabic'),
]


USE_I18N = True
USE_L10N = True

USE_TZ = True

# Define where Django should look for translation files
LOCALE_PATHS = [
    BASE_DIR / 'locale', # This is where your .po and .mo files will be
]



# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = [BASE_DIR / 'static'] if (BASE_DIR / 'static').is_dir() else []
STATIC_ROOT = BASE_DIR / "collectstatic/"

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Modifications
CLOUD_WORKER = os.environ.get("CLOUD_WORKER", "https://weathered-wave-c7f0.elprincedoca.workers.dev/")
MEDIA_WORKER_HMAC_SECRET = os.environ.get("WORKER_HMAC_SECRET") or SECRET_KEY
WORKER_RECEIPT_SECRET = os.environ.get("WORKER_RECEIPT_SECRET") or MEDIA_WORKER_HMAC_SECRET
R2_ENDPOINT_URL = os.environ.get("R2_ENDPOINT_URL") or os.environ.get("endpoint")
R2_ACCESS_KEY_ID = os.environ.get("R2_ACCESS_KEY_ID") or os.environ.get("key_id")
R2_SECRET_ACCESS_KEY = os.environ.get("R2_SECRET_ACCESS_KEY") or os.environ.get("access_key")
R2_BUCKET_NAME = os.environ.get("R2_BUCKET_NAME") or os.environ.get("bucket") or ""
CLOUDFLARE_ACCOUNT_ID = os.environ.get("CLOUDFLARE_ACCOUNT_ID", "")
CLOUDFLARE_API_TOKEN = os.environ.get("CLOUDFLARE_API_TOKEN", "")

# Change Auth Model
AUTH_USER_MODEL = 'management_system.User'

# Crispy Form
CRISPY_ALLOWED_TEMPLATE_PACKS = "bootstrap5"
CRISPY_TEMPLATE_PACK = "bootstrap5"

# Enable Multilangual
USE_I18N = True


# Sessions expiry
SESSION_COOKIE_AGE = 60 * 60 * 24 * 7 # Seconds Minutes Hours Days

# Make tempalte always use absolute urls
FORCE_SCRIPT_NAME = '/'

# Email — set EMAIL_HOST_USER and EMAIL_HOST_PASSWORD for Gmail SMTP
EMAIL_BACKEND = os.getenv('DJANGO_EMAIL_BACKEND', 'django.core.mail.backends.console.EmailBackend')
EMAIL_HOST = os.getenv('DJANGO_EMAIL_HOST', 'smtp.gmail.com')
EMAIL_PORT = int(os.getenv('DJANGO_EMAIL_PORT', '587'))
EMAIL_USE_TLS = os.getenv('DJANGO_EMAIL_USE_TLS', 'True').lower() in ('true', '1', 'yes')
EMAIL_TIMEOUT = int(os.getenv('DJANGO_EMAIL_TIMEOUT', '20'))
EMAIL_HOST_USER = os.getenv('DJANGO_EMAIL_HOST_USER', '')
EMAIL_HOST_PASSWORD = os.getenv('DJANGO_EMAIL_HOST_PASSWORD', '')
DEFAULT_FROM_EMAIL = os.getenv('DJANGO_DEFAULT_FROM_EMAIL', 'noreply@bibleinstitute.edu')
LOGIN_URL_REVERSE = 'user_login'
LOGIN_URL = reverse_lazy('user_login')
LOGIN_REDIRECT_URL = 'home'

ADMIN_EMAIL = os.getenv('DJANGO_ADMIN_EMAIL', '')

# Logging
LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "verbose": {
            "format": "{levelname} {asctime} {module} {process:d} {thread:d} {message}",
            "style": "{",
        }
    },
    "handlers": {
        "console": {
            "level": "INFO",
            "class": "logging.StreamHandler",
            "formatter": "verbose"
        },
    },
    "root": {
        "handlers": ["console"],
        "level": "DEBUG",
    },
    "loggers": {
        "django": {
            "handlers": ["console"],
            "level": "DEBUG",
            "propagate": True,
        },
    },
}
