"""
Django settings for learning_platform project.

Generated by 'django-admin startproject' using Django 5.1.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
from urllib.parse import urlsplit
import os
from dotenv import load_dotenv
from django.core.exceptions import ImproperlyConfigured
from django.urls import reverse_lazy
load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('DJANGO_SECRET_KEY')
if not SECRET_KEY:
    raise ImproperlyConfigured('DJANGO_SECRET_KEY environment variable is required')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DJANGO_DEBUG', '').lower() in ('true', '1', 'yes')
STATIC_ASSET_VERSION = os.getenv('STATIC_ASSET_VERSION', 'dev')

# Nginx terminates TLS and forwards the original protocol. Secure cookie
# defaults turn on automatically for production while remaining convenient for
# local HTTP development.
SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
SESSION_COOKIE_SECURE = os.getenv(
    "DJANGO_SESSION_COOKIE_SECURE", "False" if DEBUG else "True"
).lower() in ("true", "1", "yes")
CSRF_COOKIE_SECURE = os.getenv(
    "DJANGO_CSRF_COOKIE_SECURE", "False" if DEBUG else "True"
).lower() in ("true", "1", "yes")

def _env_csv(name, default=''):
    return [value.strip() for value in os.getenv(name, default).split(',') if value.strip()]


def _env_bool(name, default=False):
    return os.getenv(name, str(default)).lower() in ('true', '1', 'yes')


def _is_plain_domain(host):
    return (
        host
        and host != '*'
        and not host.startswith(('.', '*'))
        and '.' in host
        and not host.replace('.', '').isdigit()
        and ':' not in host
    )


ALLOWED_HOSTS = []
for configured_host in _env_csv('DJANGO_ALLOWED_HOSTS', '*'):
    configured_host = configured_host.strip()
    if configured_host.startswith('*.'):
        configured_host = f'.{configured_host[2:]}'
    if configured_host:
        ALLOWED_HOSTS.append(configured_host)
        if _is_plain_domain(configured_host):
            ALLOWED_HOSTS.append(f'.{configured_host}')
ALLOWED_HOSTS = list(dict.fromkeys(ALLOWED_HOSTS))

CSRF_TRUSTED_ORIGINS = []
for configured_origin in _env_csv('DJANGO_CSRF_TRUSTED_ORIGINS'):
    configured_origin = configured_origin.rstrip('/')
    if not configured_origin:
        continue
    CSRF_TRUSTED_ORIGINS.append(configured_origin)
    origin_parts = urlsplit(configured_origin)
    origin_host = origin_parts.hostname or ''
    if (
        origin_parts.scheme in ('http', 'https')
        and not origin_parts.port
        and not origin_parts.username
        and _is_plain_domain(origin_host)
    ):
        CSRF_TRUSTED_ORIGINS.append(f'{origin_parts.scheme}://*.{origin_host}')

# Django requires explicit ports for CSRF trusted origins. Generate the
# configured localhost development ports while keeping production origins
# explicit. Bearer-authenticated mobile API writes are CSRF-exempt.
ALLOW_LOCALHOST_ORIGINS = _env_bool('DJANGO_ALLOW_LOCALHOST_ORIGINS', DEBUG)
if ALLOW_LOCALHOST_ORIGINS:
    localhost_ports = _env_csv(
        'DJANGO_LOCALHOST_PORTS',
        '3000,4173,5173,8000,8080,8081,8082,8443',
    )
    for localhost_host in ('localhost', '127.0.0.1', '[::1]'):
        for port in localhost_ports:
            if port.isdigit() and 0 < int(port) <= 65535:
                for scheme in ('http', 'https'):
                    CSRF_TRUSTED_ORIGINS.append(f'{scheme}://{localhost_host}:{port}')
CSRF_TRUSTED_ORIGINS = list(dict.fromkeys(CSRF_TRUSTED_ORIGINS))

# The built-in MobileApiCorsMiddleware consumes these settings; no CORS
# dependency is needed for bearer-authenticated API requests.
CORS_ALLOWED_ORIGINS = _env_csv('DJANGO_CORS_ALLOWED_ORIGINS')
CORS_ALLOW_ALL_ORIGINS = DEBUG and _env_bool('DJANGO_CORS_ALLOW_ALL_ORIGINS')

TIME_ZONE = os.getenv('DJANGO_TIME_ZONE', 'Africa/Cairo')
DJANGO_SITE_DOMAIN = os.getenv('DJANGO_SITE_DOMAIN', '').rstrip('/')

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # Third Parties
    "django_extensions",
    'crispy_forms',
    'crispy_bootstrap5',
    # Applications
    'management_system'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.locale.LocaleMiddleware', # Add this for localization
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'management_system.middleware.RequestObservabilityMiddleware',
    'management_system.middleware.MobileApiCorsMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'management_system.middleware.SessionExpiryUpdate'
]

ROOT_URLCONF = 'learning_platform.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'django.template.context_processors.i18n',
                'management_system.context_processors.static_asset_version',
                'management_system.context_processors.localized_alternate_urls',
            ],
        },
    },
]

WSGI_APPLICATION = 'learning_platform.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.getenv('POSTGRES_DB', 'lms_database'),
        'USER': os.getenv('POSTGRES_USER', 'lms_user'),
        'PASSWORD': os.getenv('POSTGRES_PASSWORD', 'dev_password_change_me'),
        'HOST': os.getenv('POSTGRES_HOST', 'localhost'),
        'PORT': os.getenv('POSTGRES_PORT', '5432'),
    },
    'sqlite_source': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.getenv('SQLITE_SOURCE_PATH', str(BASE_DIR / 'db.sqlite3')),
    },
}

# Celery (Redis broker / result backend — defaults to the redis service on lms_network)
CELERY_BROKER_URL = os.getenv("CELERY_BROKER_URL") or os.getenv(
    "REDIS_URL", "redis://redis:6379/0"
)
CELERY_RESULT_BACKEND = os.getenv("CELERY_RESULT_BACKEND") or os.getenv(
    "REDIS_URL", "redis://redis:6379/0"
)
CELERY_BROKER_CONNECTION_RETRY_ON_STARTUP = True
REDIS_CACHE_URL = os.getenv("REDIS_CACHE_URL", "redis://redis:6379/1")
CACHES = {
    "default": {
        "BACKEND": "django.core.cache.backends.redis.RedisCache",
        "LOCATION": REDIS_CACHE_URL,
        "TIMEOUT": None,
    },
}
CELERY_TASK_TRACK_STARTED = True
CELERY_TIMEZONE = TIME_ZONE
CELERY_IMPORTS = (
    "management_system.telegram_tasks",
    "management_system.media_tasks",
    "management_system.mobile_push_tasks",
    "management_system.mobile_otp_tasks",
)
CELERY_TASK_ROUTES = {
    "management_system.media_tasks.*": {"queue": "media"},
}
CELERY_BEAT_SCHEDULE = {
    "recover-pending-media-jobs": {
        "task": "management_system.media_tasks.recover_pending_media_jobs",
        "schedule": 60.0,
        "kwargs": {"limit": 100},
    },
    "dispatch-due-mobile-push": {
        "task": "management_system.mobile_push_tasks.dispatch_due_mobile_push",
        "schedule": 15.0,
        "kwargs": {"limit": 1000},
    },
    "process-mobile-push-receipts": {
        "task": "management_system.mobile_push_tasks.process_mobile_push_receipts",
        "schedule": 30.0,
        "kwargs": {"limit": 1000},
    },
}

# Expo Push Service is the only mobile push provider. The access token is
# server-only and is never rendered, logged, or returned by an application API.
def _expo_endpoint(setting_name: str, default_path: str) -> str:
    value = os.getenv(setting_name, f"https://exp.host{default_path}").strip()
    parsed = urlsplit(value)
    if (
        parsed.scheme != "https"
        or parsed.hostname != "exp.host"
        or parsed.username
        or parsed.password
        or parsed.query
        or parsed.fragment
        or parsed.path != default_path
    ):
        raise ImproperlyConfigured(f"{setting_name} must be an exact HTTPS Expo endpoint.")
    return value


EXPO_PUSH_SEND_URL = _expo_endpoint("EXPO_PUSH_SEND_URL", "/--/api/v2/push/send")
EXPO_PUSH_RECEIPTS_URL = _expo_endpoint("EXPO_PUSH_RECEIPTS_URL", "/--/api/v2/push/getReceipts")
EXPO_PUSH_ACCESS_TOKEN = os.getenv("EXPO_PUSH_ACCESS_TOKEN", "")
EXPO_PUSH_TIMEOUT_SECONDS = float(os.getenv("EXPO_PUSH_TIMEOUT_SECONDS", "15"))
# Expo documents a 600 notifications/second service ceiling. Five requests per
# second at 100 messages per request keeps this application below that ceiling.
EXPO_PUSH_REQUESTS_PER_SECOND = int(os.getenv("EXPO_PUSH_REQUESTS_PER_SECOND", "5"))
EXPO_PUSH_SEND_BATCH_SIZE = 100
EXPO_PUSH_RECEIPT_BATCH_SIZE = 1000

# Server-side media processing limits. Native FFmpeg runs only in the
# dedicated media worker; these values are also exposed in the worker's
# Compose environment for operational inspection.
MEDIA_WORK_DIR = os.getenv("MEDIA_WORK_DIR", "/var/lib/lms-media-processing")
MEDIA_MAX_SOURCE_SIZE = int(os.getenv("MEDIA_MAX_SOURCE_SIZE", str(2 * 1024 ** 3)))
MEDIA_MAX_DURATION_SECONDS = int(os.getenv("MEDIA_MAX_DURATION_SECONDS", str(3 * 60 * 60)))
MEDIA_JOB_TIMEOUT_SECONDS = int(os.getenv("MEDIA_JOB_TIMEOUT_SECONDS", str(2 * 60 * 60)))
MEDIA_SEGMENT_SECONDS = int(os.getenv("MEDIA_SEGMENT_SECONDS", "12"))
MEDIA_SOURCE_RETENTION_HOURS = int(os.getenv("MEDIA_SOURCE_RETENTION_HOURS", "24"))
MEDIA_FAILED_SOURCE_RETENTION_HOURS = int(os.getenv("MEDIA_FAILED_SOURCE_RETENTION_HOURS", "72"))
MEDIA_SUCCESSFUL_JOB_RETENTION_DAYS = int(os.getenv("MEDIA_SUCCESSFUL_JOB_RETENTION_DAYS", "90"))
MEDIA_WORKER_CONCURRENCY = int(os.getenv("MEDIA_WORKER_CONCURRENCY", "1"))

# Keep Django's request ceiling aligned with the Nginx 2 GiB upload ceiling.
# Uploaded files above FILE_UPLOAD_MAX_MEMORY_SIZE are spooled to disk by
# Django's temporary-file upload handler rather than held in process memory.
DATA_UPLOAD_MAX_MEMORY_SIZE = int(
    os.getenv("DJANGO_DATA_UPLOAD_MAX_MEMORY_SIZE", str(2 * 1024 ** 3))
)
FILE_UPLOAD_MAX_MEMORY_SIZE = int(
    os.getenv("DJANGO_FILE_UPLOAD_MAX_MEMORY_SIZE", str(10 * 1024 ** 2))
)

# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en'
LANGUAGES = [
    ('en', 'English'),
    ('ar', 'Arabic'),
]


USE_I18N = True
USE_L10N = True

USE_TZ = True

# Define where Django should look for translation files
LOCALE_PATHS = [
    BASE_DIR / 'locale', # This is where your .po and .mo files will be
]



# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = [BASE_DIR / 'static'] if (BASE_DIR / 'static').is_dir() else []
STATIC_ROOT = BASE_DIR / "collectstatic/"

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Modifications
CLOUD_WORKER = os.environ.get("CLOUD_WORKER", "").rstrip("/")
MEDIA_WORKER_HMAC_SECRET = os.environ.get("WORKER_HMAC_SECRET") or SECRET_KEY
WORKER_RECEIPT_SECRET = os.environ.get("WORKER_RECEIPT_SECRET") or MEDIA_WORKER_HMAC_SECRET
TELEGRAM_ENCRYPTION_KEY = os.environ.get("TELEGRAM_ENCRYPTION_KEY") or SECRET_KEY
R2_ENDPOINT_URL = os.environ.get("R2_ENDPOINT_URL") or os.environ.get("endpoint")
R2_ACCESS_KEY_ID = os.environ.get("R2_ACCESS_KEY_ID") or os.environ.get("key_id")
R2_SECRET_ACCESS_KEY = os.environ.get("R2_SECRET_ACCESS_KEY") or os.environ.get("access_key")
R2_BUCKET_NAME = os.environ.get("R2_BUCKET_NAME") or os.environ.get("bucket") or ""
TELEGRAM_R2_BUCKET_NAME = os.environ.get("TELEGRAM_R2_BUCKET_NAME", "")
CLOUDFLARE_ACCOUNT_ID = os.environ.get("CLOUDFLARE_ACCOUNT_ID", "")
CLOUDFLARE_API_TOKEN = os.environ.get("CLOUDFLARE_API_TOKEN", "")

# Change Auth Model
AUTH_USER_MODEL = 'management_system.User'

# Crispy Form
CRISPY_ALLOWED_TEMPLATE_PACKS = "bootstrap5"
CRISPY_TEMPLATE_PACK = "bootstrap5"

# Enable Multilangual
USE_I18N = True


# Sessions expiry
SESSION_COOKIE_AGE = 60 * 60 * 24 * 7 # Seconds Minutes Hours Days

# Make tempalte always use absolute urls
FORCE_SCRIPT_NAME = '/'

# Email — set EMAIL_HOST_USER and EMAIL_HOST_PASSWORD for Gmail SMTP
EMAIL_BACKEND = os.getenv('DJANGO_EMAIL_BACKEND', 'django.core.mail.backends.console.EmailBackend')
EMAIL_HOST = os.getenv('DJANGO_EMAIL_HOST', 'smtp.gmail.com')
EMAIL_PORT = int(os.getenv('DJANGO_EMAIL_PORT', '587'))
EMAIL_USE_TLS = os.getenv('DJANGO_EMAIL_USE_TLS', 'True').lower() in ('true', '1', 'yes')
EMAIL_TIMEOUT = int(os.getenv('DJANGO_EMAIL_TIMEOUT', '20'))
EMAIL_HOST_USER = os.getenv('DJANGO_EMAIL_HOST_USER', '')
EMAIL_HOST_PASSWORD = os.getenv('DJANGO_EMAIL_HOST_PASSWORD', '')
DEFAULT_FROM_EMAIL = os.getenv('DJANGO_DEFAULT_FROM_EMAIL', 'noreply@bibleinstitute.edu')
LOGIN_URL_REVERSE = 'user_login'
LOGIN_URL = reverse_lazy('user_login')
LOGIN_REDIRECT_URL = 'home'

ADMIN_EMAIL = os.getenv('DJANGO_ADMIN_EMAIL', '')

# Logging
LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "verbose": {
            "format": "time={asctime} level={levelname} logger={name} event={event} request_id={request_id} route={route} method={method} status={status_code} duration_ms={duration_ms} user_id={user_id} username={username} role_id={role_id} ip={remote_ip} device={device} browser={browser} os={os} query_keys={query_keys} msg={message}",
            "style": "{",
        }
    },
    "filters": {
        "request_context": {
            "()": "management_system.middleware.RequestContextFilter",
        },
    },
    "handlers": {
        "console": {
            "level": "INFO",
            "class": "logging.StreamHandler",
            "formatter": "verbose",
            "filters": ["request_context"],
        },
    },
    "root": {
        "handlers": ["console"],
        "level": "DEBUG",
    },
    "loggers": {
        "django": {
            "handlers": ["console"],
            "level": "DEBUG",
            "propagate": False,
        },
    },
}
