COMMON = {
    'ar': {
        'site_name': 'معهد الكتاب المقدس', 'site_location': 'بالمعادي',
        'site_tagline': 'دراسة أكاديمية بروح كنسية', 'home': 'الرئيسية', 'about': 'عن المعهد',
        'study': 'نظام الدراسة', 'subjects_label': 'المواد', 'admission': 'الالتحاق',
        'news': 'الأخبار', 'contact': 'اتصل بنا', 'student_portal': 'حساب الدارس',
        'apply_now': 'قدّم الآن', 'language': 'English', 'email': 'info@bibleinstitute-eg.org',
        'address': 'كنيسة الشهيد العظيم مارجرجس، كوتسيكا، المعادي، القاهرة',
        'footer_intro': 'معهد كنسي أرثوذكسي تابع للكنيسة القبطية الأرثوذكسية، يخدم كل محبي دراسة الكتاب المقدس داخل مصر وخارجها.',
        'quick_links': 'روابط سريعة', 'contact_us': 'تواصل معنا', 'rights': 'جميع الحقوق محفوظة لمعهد الكتاب المقدس بالمعادي.',
        'page_title': 'معهد الكتاب المقدس بالمعادي',
    },
    'en': {
        'site_name': 'Bible Institute', 'site_location': 'Maadi',
        'site_tagline': 'Academic study with an ecclesial spirit', 'home': 'Home', 'about': 'About Us',
        'study': 'Study System', 'subjects_label': 'Courses', 'admission': 'Admissions',
        'news': 'News', 'contact': 'Contact', 'student_portal': 'Student Portal',
        'apply_now': 'Apply Now', 'language': 'العربية', 'email': 'info@bibleinstitute-eg.org',
        'address': 'St. George Church, Kotsika, Maadi, Cairo',
        'footer_intro': 'A Coptic Orthodox ecclesiastical institute serving everyone who loves to study Scripture in Egypt and worldwide.',
        'quick_links': 'Quick Links', 'contact_us': 'Contact Us', 'rights': 'All rights reserved to the Bible Institute in Maadi.',
        'page_title': 'Bible Institute in Maadi',
    },
}

HOME = {
    'ar': {
        'hero_kicker': 'منذ عام 2002', 'hero_title': 'لأن الكلمة حياة، ندرسها بعمق ونحياها بصدق',
        'hero_text': 'رحلة دراسية متكاملة تجمع بين المعرفة الأكاديمية والتكوين الروحي والتطبيق العملي، لتصنع شاهداً حياً للمسيح في الكنيسة والمجتمع.',
        'discover': 'اكتشف البرنامج', 'watch_message': 'شاهد كلمة نيافة الأنبا دانيال',
        'stats': [('2002', 'عام التأسيس'), ('2', 'سنتان دراسيتان'), ('11', 'مجالاً دراسياً'), ('∞', 'تعلم من أي مكان')],
        'identity_kicker': 'هوية المعهد', 'identity_title': 'بيت للدراسة، ومساحة للنمو، ورسالة للحياة',
        'identity_text': 'تأسس المعهد تحت رعاية صاحب النيافة الحبر الجليل الأنبا دانيال، مطران المعادي وتوابعها، ليقدم دراسة كتابية رصينة داخل إطار كنسي أرثوذكسي أصيل.',
        'pillars': [
            {'number': '01', 'title': 'معرفة أعمق', 'text': 'قراءة واعية للأسفار وسياقاتها ومعانيها، بأدوات تساعد الدارس على الفهم والتفسير.'},
            {'number': '02', 'title': 'حياة روحية', 'text': 'ليست المعرفة غاية في ذاتها؛ بل طريقاً لعلاقة أعمق بالله وحياة تتشكل بكلمته.'},
            {'number': '03', 'title': 'شهادة مؤثرة', 'text': 'تأهيل خدام ودارسين يترجمون ما تعلموه إلى حضور إيجابي في الأسرة والكنيسة والوطن.'},
        ],
        'news_kicker': 'آخر الأخبار', 'news_title': 'العام الدراسي 2026–2027',
        'news_text': 'تبدأ الدراسة يوم الأحد 20 سبتمبر 2026 وتستمر حتى نهاية مايو 2027. الدراسة النظامية يومي الأحد والثلاثاء من السادسة حتى التاسعة مساءً.',
        'news_badge': 'التقديم متاح', 'news_link': 'اعرف مواعيد ونظام الدراسة',
        'path_kicker': 'اختر مسارك', 'path_title': 'نفس المحتوى، بالطريقة الأنسب لظروفك',
        'paths': [
            {'label': 'داخل القاهرة والجيزة', 'title': 'الدراسة النظامية', 'text': 'محاضرات داخل قاعات المعهد بكنيسة الشهيد العظيم مارجرجس بكوتسيكا، مع تواصل مباشر مع المحاضرين.', 'action': 'تفاصيل الحضور'},
            {'label': 'المحافظات وخارج مصر', 'title': 'التعلم الذاتي Online', 'text': 'محاضرات فيديو وصوت ومواد علمية متاحة على الموقع، وامتحانات إلكترونية تراعي فروق التوقيت.', 'action': 'تفاصيل الدراسة Online'},
        ],
        'quote': 'كل مسيحي يحيا بالكتاب المقدس مؤهل للشهادة الحية للسيد المسيح في كل الظروف.',
        'quote_label': 'رؤية المعهد', 'curriculum_kicker': 'ماذا ستدرس؟', 'curriculum_title': 'منهج واسع يربط النص بسياقه وحياة الكنيسة',
        'curriculum_text': 'من أسفار العهدين وشخصياتهما إلى الجغرافيا والفنون الكتابية والقراءات الكنسية والمفاهيم اللاهوتية.',
        'curriculum_action': 'استعرض المواد بالتفصيل', 'video_kicker': 'من قلب المعهد', 'video_title': 'كلمة المشرف العام',
        'video_text': 'استمع إلى كلمة صاحب النيافة الحبر الجليل الأنبا دانيال عن رسالة المعهد ودور دراسة الكتاب المقدس في حياة الإنسان.',
        'cta_title': 'ابدأ رحلة أعمق مع الكتاب المقدس', 'cta_text': 'الجميع مدعو للدراسة والفهم والتعمق، حضورياً أو عن بُعد.',
    },
    'en': {
        'hero_kicker': 'Since 2002', 'hero_title': 'Because the Word is life, we study it deeply and live it faithfully',
        'hero_text': 'An integrated journey combining academic knowledge, spiritual formation, and practical application—forming living witnesses for Christ in Church and society.',
        'discover': 'Explore the Program', 'watch_message': 'Watch Bishop Daniel’s Message',
        'stats': [('2002', 'Founded'), ('2', 'Academic Years'), ('11', 'Fields of Study'), ('∞', 'Learn Anywhere')],
        'identity_kicker': 'Our Identity', 'identity_title': 'A home for study, a place for growth, a mission for life',
        'identity_text': 'Founded under the patronage of His Grace Bishop Daniel, Metropolitan of Maadi and its districts, the Institute offers rigorous biblical study within an authentic Coptic Orthodox setting.',
        'pillars': [
            {'number': '01', 'title': 'Deeper Knowledge', 'text': 'Thoughtful reading of Scripture, its contexts and meanings, with tools that support sound understanding and interpretation.'},
            {'number': '02', 'title': 'Spiritual Life', 'text': 'Knowledge is not an end in itself, but a path toward deeper fellowship with God and a life shaped by His Word.'},
            {'number': '03', 'title': 'Living Witness', 'text': 'Preparing students and servants to translate learning into a positive presence in family, Church, and nation.'},
        ],
        'news_kicker': 'Latest News', 'news_title': 'Academic Year 2026–2027',
        'news_text': 'Studies begin Sunday, September 20, 2026 and continue through the end of May 2027. On-campus classes meet Sundays and Tuesdays, 6–9 PM.',
        'news_badge': 'Admissions Open', 'news_link': 'View dates and study system',
        'path_kicker': 'Choose Your Path', 'path_title': 'The same formation, delivered around your life',
        'paths': [
            {'label': 'Greater Cairo & Giza', 'title': 'On-Campus Study', 'text': 'Lectures at St. George Church in Kotsika, with direct contact and discussion with faculty.', 'action': 'On-campus details'},
            {'label': 'Other governorates & abroad', 'title': 'Online Self-Paced Study', 'text': 'Video, audio, and study materials online, with electronic exams designed around global time zones.', 'action': 'Online study details'},
        ],
        'quote': 'Every Christian who lives by Scripture is equipped to be a living witness for Christ in every circumstance.',
        'quote_label': 'Our Vision', 'curriculum_kicker': 'What Will You Study?', 'curriculum_title': 'A broad curriculum connecting text, context, and Church life',
        'curriculum_text': 'From the Old and New Testaments and their people to biblical geography, literary forms, lectionary readings, and theological concepts.',
        'curriculum_action': 'Explore all courses', 'video_kicker': 'From the Institute', 'video_title': 'A Message from Our General Supervisor',
        'video_text': 'Hear His Grace Bishop Daniel speak about the Institute’s mission and the place of Scripture in a life of faith.',
        'cta_title': 'Begin a deeper journey with Scripture', 'cta_text': 'Everyone is invited to study, understand, and go deeper—on campus or online.',
    },
}

ABOUT = {
    'ar': {
        'page_title': 'عن المعهد', 'hero_kicker': 'من نحن', 'hero_title': 'أكثر من دراسة… تكوين إنسان يعيش بالكلمة',
        'hero_text': 'نخدم رؤية واضحة: أن يصبح الكتاب المقدس حياة يومية، ومصدراً للنمو، وقوة للشهادة.',
        'story_kicker': 'قصتنا', 'story_title': 'البداية من كوتسيكا، والرسالة إلى كل العالم',
        'story_text_1': 'في عام 2002م تم إنشاء المعهد بكنيسة الشهيد العظيم مارجرجس بكوتسيكا، تحت رعاية صاحب النيافة الحبر الجليل الأنبا دانيال، مطران المعادي وتوابعها.',
        'story_text_2': 'منذ البداية، لم يكن الهدف تقديم معلومات فقط، بل إعداد دارسين روحياً وعلمياً من خلال دراسة أكاديمية وروحية وعملية للكتاب المقدس.',
        'timeline': [('2002', 'تأسيس المعهد في كنيسة مارجرجس بكوتسيكا'), ('اليوم', 'دراسة نظامية وOnline لدارسين داخل مصر وخارجها'), ('المستقبل', 'جيل يحيا بالكلمة ويشهد للمسيح في كل مجالات الحياة')],
        'purpose_kicker': 'بوصلتنا', 'purpose_title': 'رؤية ورسالة وهدف واحد: أن تصير الكلمة حياة',
        'purpose': [
            {'title': 'هدفنا', 'text': 'إعداد الدارسين روحياً وعلمياً لفهم أسلوب وكلمات ومعاني الكتاب المقدس بصورة أكثر عمقاً، وتطبيق ما يتعلمونه في الحياة والخدمة.'},
            {'title': 'رؤيتنا', 'text': 'كل مسيحي يحيا بالكتاب المقدس مؤهل للشهادة الحية للسيد المسيح، وقادر على التأثير الإيجابي في الأسرة والكنيسة والمجتمع والوطن.'},
            {'title': 'رسالتنا', 'text': 'تأهيل أعضاء الكنيسة وإعداد كوادر من الخدام القادرين على تكوين جيل يشهد للمسيح شهادة كتابية حية في كل نواحي حياته.'},
        ],
        'values_kicker': 'ما يميز تجربتنا', 'values_title': 'قيم تتحول إلى ممارسة',
        'values': [('الأصالة', 'دراسة تنطلق من إيمان الكنيسة القبطية الأرثوذكسية وتراثها الحي.'), ('العمق', 'الاقتراب من النص بدقة واحترام لسياقه وتكامله.'), ('الشركة', 'تعلم ينمو بالحوار والتواصل المستمر بين الدارسين والمحاضرين.'), ('الخدمة', 'معرفة تقود إلى محبة عملية وشهادة مؤثرة.')],
        'leadership_kicker': 'الرعاية والقيادة', 'leadership_title': 'خدمة تحت رعاية كنسية',
        'leaders': [
            {'role': 'الرئيس الأعلى للمعاهد والكليات الإكليريكية', 'name': 'قداسة البابا تواضروس الثاني', 'detail': 'بابا الإسكندرية وبطريرك الكرازة المرقسية'},
            {'role': 'المشرف العام على المعهد', 'name': 'نيافة الأنبا دانيال', 'detail': 'مطران المعادي وتوابعها'},
        ],
        'place_kicker': 'مقر المعهد', 'place_title': 'في قلب المعادي', 'place_text': 'تُعقد المحاضرات في القاعات الخاصة بالمعهد بكنيسة الشهيد العظيم مارجرجس بكوتسيكا، في بيئة تجمع بين الدراسة والشركة والحياة الكنسية.',
    },
    'en': {
        'page_title': 'About Us', 'hero_kicker': 'Who We Are', 'hero_title': 'More than study—forming people who live by the Word',
        'hero_text': 'We serve a clear vision: Scripture becoming daily life, a source of growth, and power for witness.',
        'story_kicker': 'Our Story', 'story_title': 'From Kotsika to learners around the world',
        'story_text_1': 'The Institute was founded in 2002 at St. George Church in Kotsika under the patronage of His Grace Bishop Daniel, Metropolitan of Maadi and its districts.',
        'story_text_2': 'From the beginning, the purpose was never information alone, but the spiritual and academic formation of students through scholarly, devotional, and practical study of Scripture.',
        'timeline': [('2002', 'The Institute is founded at St. George Church, Kotsika'), ('Today', 'On-campus and online study for learners in Egypt and abroad'), ('Tomorrow', 'A generation that lives by the Word and witnesses for Christ in every sphere')],
        'purpose_kicker': 'Our Compass', 'purpose_title': 'One vision, mission, and purpose: the Word becoming life',
        'purpose': [
            {'title': 'Our Purpose', 'text': 'To prepare students spiritually and academically to understand the style, words, and meanings of Scripture more deeply and apply their learning in life and ministry.'},
            {'title': 'Our Vision', 'text': 'Every Christian who lives by Scripture is equipped to witness for Christ and make a positive difference in family, Church, society, and nation.'},
            {'title': 'Our Mission', 'text': 'To equip Church members and servant-leaders who can form a generation that offers a living biblical witness in every part of life.'},
        ],
        'values_kicker': 'The Experience', 'values_title': 'Values translated into practice',
        'values': [('Authenticity', 'Study rooted in the faith and living heritage of the Coptic Orthodox Church.'), ('Depth', 'Approaching the text carefully, respecting its context and unity.'), ('Community', 'Learning that grows through dialogue and continuous faculty interaction.'), ('Service', 'Knowledge that leads to practical love and meaningful witness.')],
        'leadership_kicker': 'Patronage & Leadership', 'leadership_title': 'Serving under ecclesiastical care',
        'leaders': [
            {'role': 'Supreme Head of Seminaries and Theological Institutes', 'name': 'His Holiness Pope Tawadros II', 'detail': 'Pope of Alexandria and Patriarch of the See of St. Mark'},
            {'role': 'General Supervisor of the Institute', 'name': 'His Grace Bishop Daniel', 'detail': 'Metropolitan of Maadi and its districts'},
        ],
        'place_kicker': 'Our Campus', 'place_title': 'In the heart of Maadi', 'place_text': 'Lectures take place in the Institute’s halls at St. George Church in Kotsika, an environment joining study, fellowship, and Church life.',
    },
}

COURSES = {
    'ar': {
        'page_title': 'نظام الدراسة والمواد', 'hero_kicker': 'رحلتك الدراسية', 'hero_title': 'برنامج واضح، مرن، وعميق',
        'hero_text': 'سنتان دراسيتان، أربعة فصول، ونظام ساعات معتمدة صُمم ليمنحك فهماً متدرجاً ومتكاملاً للكتاب المقدس.',
        'overview': [('20 سبتمبر 2026', 'بداية الدراسة'), ('الأحد والثلاثاء', 'أيام الحضور'), ('6–9 مساءً', 'موعد المحاضرات'), ('50%', 'نسبة النجاح')],
        'system_kicker': 'نظام الدراسة', 'system_title': 'كل ما تحتاج معرفته قبل أن تبدأ',
        'system_items': [
            {'title': 'المدة والتقسيم', 'text': 'الدراسة على سنتين، وتنقسم كل سنة إلى فصلين دراسيين. يُمنح الدارس شهادة إتمام الدراسة في حفل التخرج السنوي.'},
            {'title': 'الدراسة النظامية', 'text': 'حضور يومي الأحد والثلاثاء من 6م إلى 9م في مقر المعهد، للدارسين المقيمين في القاهرة الكبرى والجيزة.'},
            {'title': 'الدراسة Online', 'text': 'تعلم ذاتي للمحافظات وخارج مصر، مع محاضرات فيديو وصوت ومواد علمية متاحة عبر الموقع.'},
            {'title': 'الامتحانات', 'text': 'جميع الامتحانات Online، وتحدد الإدارة مدتها بما يناسب فروق التوقيت للدارسين خارج مصر.'},
            {'title': 'التقييم والانتقال', 'text': 'نسبة النجاح في كل مادة 50%، ولا ينتقل الدارس إلى السنة التالية إذا رسب في أكثر من مادتين.'},
            {'title': 'الكتب والمؤتمر', 'text': 'يوفر المعهد الكتب والملازم رقمياً أو من المقر، وينظم مؤتمراً سنوياً إلزامياً لدراسة أحد الأسفار بالتفصيل.'},
        ],
        'curriculum_kicker': 'المواد الدراسية', 'curriculum_title': 'خريطة تعلم متكاملة',
        'curriculum_intro': 'تغطي الدراسة النص والسياق والتاريخ واللاهوت والحياة الكنسية، بحيث يرى الدارس الصورة الكبرى دون أن يفقد جمال التفاصيل.',
        'subjects': [
            ('شخصيات الكتاب المقدس', 'دراسة شخصيات العهدين وما تكشفه رحلاتهم عن عمل الله والإنسان.'),
            ('أسفار العهد القديم', 'مدخل منظم إلى الأسفار وخلفياتها ورسالتها وموقعها في قصة الخلاص.'),
            ('العهد الجديد', 'فهم الأناجيل والسفر التاريخي والرسائل والرؤيا في سياقها.'),
            ('الفنون الكتابية', 'تمييز السرد والشعر والنبوة والحكمة والرسالة وأثر النوع الأدبي في التفسير.'),
            ('نقد الكتاب واستحالة تحريفه', 'التعرف إلى انتقال النص وشواهده والأسس التي تؤكد أمانته.'),
            ('الأسرار الكنسية والكتاب', 'استكشاف الجذور الكتابية للحياة السرائرية في الكنيسة.'),
            ('القراءات الكنسية – القطمارس', 'فهم ترتيب القراءات وعلاقتها بالمواسم والأعياد والليتورجيا.'),
            ('جغرافيا الكتاب المقدس', 'ربط الأحداث بالأماكن والطرق والبيئة في العهدين.'),
            ('خلفيات العهد القديم', 'التاريخ والثقافات والعادات التي تساعد على قراءة النص في عالمه.'),
            ('ما بين العهدين والأسفار القانونية الثانية', 'فهم الفترة التي مهدت للعهد الجديد والتعرف إلى الأسفار القانونية الثانية.'),
            ('لاهوت رسائل بولس الرسول', 'قراءة المفاهيم اللاهوتية والعقائدية الكبرى داخل رسائل الرسول بولس.'),
        ],
        'faculty_kicker': 'هيئة التدريس', 'faculty_title': 'تعلم على أيدي خدام ومتخصصين',
        'faculty': ['نيافة الأنبا دانيال', 'الدكتور القمص داود مكرم', 'القس بولس ميلاد', 'القس رافائيل عبد الملاك', 'القمص صموئيل ميشيل', 'القس موسى ميشيل', 'د. إميل بولس', 'م. ماجد مكرم', 'د. عماد صبحي', 'د. ماجد لبيب', 'أ. بطرس إسحق', 'م. جورج مرقس'],
        'fees_kicker': 'المصروفات', 'fees_title': 'استثمار بسيط في رحلة عميقة', 'inside': 'داخل مصر', 'outside': 'خارج مصر',
        'egp': '850 جنيه مصري', 'usd': '75 دولاراً أمريكياً', 'fees_note': 'الرسوم لا تشمل الكتب والملازم الاختيارية أو مصروفات الشحن، وتُحسب وفق التكلفة الفعلية.',
        'register_kicker': 'الالتحاق', 'register_title': 'أربع خطوات وتبدأ الرحلة',
        'steps': [('املأ الطلب', 'أنشئ حسابك واستكمل بيانات طلب الالتحاق.'), ('اختر نظام الدراسة', 'حدد الدراسة النظامية أو Online وفق محل إقامتك.'), ('سدّد المصروفات', 'عبر إنستاباي أو المحفظة الإلكترونية أو نقداً بالمقر أو التحويل البنكي من خارج مصر.'), ('تفعيل الحساب', 'بعد استكمال الإجراءات يتم تفعيل دخولك إلى مواد ومحاضرات المعهد.')],
        'requirements_title': 'شروط الالتحاق', 'requirements_text': 'الجميع مدعو لدراسة وفهم والتعمق في الكتاب المقدس، سواء من خلال الدراسة النظامية أو الدراسة عن بُعد Online.',
        'calendar_title': 'الإجازات الدراسية', 'calendar': [('نصف العام', 'فترة عيد الميلاد وعيد الغطاس'), ('عيد القيامة', 'من الخميس السابق لجمعة ختام الصوم وحتى الأسبوع التالي للعيد')],
        'faq_kicker': 'أسئلة شائعة', 'faq_title': 'إجابات سريعة قبل التسجيل',
        'faq': [('هل الدراسة Online متاحة داخل القاهرة؟', 'وفق نظام المعهد، التعلم الذاتي مخصص للدارسين في المحافظات وخارج مصر، بينما يدرس المقيمون في القاهرة الكبرى والجيزة حضورياً.'), ('كيف أحصل على الكتب؟', 'تُرفع المواد على موقع المعهد، ويمكن الحصول على النسخ المطبوعة من المقر أو شحنها خارج القاهرة الكبرى.'), ('كيف تعقد الامتحانات؟', 'تُعقد جميع الامتحانات على موقع المعهد، مع مدة مناسبة لفروق التوقيت خارج مصر.')],
    },
    'en': {
        'page_title': 'Study System & Courses', 'hero_kicker': 'Your Learning Journey', 'hero_title': 'Clear, flexible, and deeply formative',
        'hero_text': 'Two academic years, four terms, and a credit-hour system designed to build a progressive, integrated understanding of Scripture.',
        'overview': [('Sep 20, 2026', 'Studies Begin'), ('Sun & Tue', 'Campus Days'), ('6–9 PM', 'Lecture Time'), ('50%', 'Passing Grade')],
        'system_kicker': 'Study System', 'system_title': 'Everything you need to know before you begin',
        'system_items': [
            {'title': 'Duration & Terms', 'text': 'The program runs for two years, each divided into two terms. Graduates receive a completion certificate at the annual ceremony.'},
            {'title': 'On-Campus Study', 'text': 'Classes meet Sundays and Tuesdays, 6–9 PM, at the Institute for residents of Greater Cairo and Giza.'},
            {'title': 'Online Study', 'text': 'Self-paced learning for other governorates and abroad, with video, audio, and study materials available online.'},
            {'title': 'Examinations', 'text': 'All exams take place online, with windows set to accommodate students in different time zones.'},
            {'title': 'Assessment & Progression', 'text': 'The passing grade is 50% per course. Students failing more than two courses may not progress to the next year.'},
            {'title': 'Books & Conference', 'text': 'Books and notes are available digitally or from campus. An annual required conference studies a biblical book in depth.'},
        ],
        'curriculum_kicker': 'Curriculum', 'curriculum_title': 'An integrated map for learning',
        'curriculum_intro': 'The program spans text, context, history, theology, and Church life—helping students see the whole story without losing the beauty of its details.',
        'subjects': [
            ('Biblical Characters', 'Lives from both Testaments and what their journeys reveal about God and humanity.'),
            ('Old Testament Books', 'A structured introduction to their backgrounds, message, and place in salvation history.'),
            ('The New Testament', 'The Gospels, Acts, Epistles, and Revelation read within their contexts.'),
            ('Biblical Literary Forms', 'Narrative, poetry, prophecy, wisdom, and letters—and how genre shapes interpretation.'),
            ('Textual Criticism & Preservation', 'How the text was transmitted, its witnesses, and the foundations for confidence in its integrity.'),
            ('Sacraments & Scripture', 'Exploring the biblical roots of the Church’s sacramental life.'),
            ('Lectionary Readings', 'Understanding the Katameros and the relationship of readings to seasons, feasts, and liturgy.'),
            ('Biblical Geography', 'Connecting events with the lands, routes, and environments of both Testaments.'),
            ('Old Testament Backgrounds', 'The histories, cultures, and customs that illuminate the biblical world.'),
            ('Intertestamental Period & Deuterocanon', 'The period preparing the New Testament and an introduction to the Deuterocanonical books.'),
            ('Theology in Pauline Epistles', 'Major theological and doctrinal themes throughout the letters of St. Paul.'),
        ],
        'faculty_kicker': 'Faculty', 'faculty_title': 'Learn from experienced clergy and specialists',
        'faculty': ['H.G. Bishop Daniel', 'Fr. Dr. Daoud Makram', 'Fr. Boulos Milad', 'Fr. Raphael Abdel Malak', 'Fr. Samuel Michel', 'Fr. Moussa Michel', 'Dr. Emil Boulos', 'Eng. Maged Makram', 'Dr. Emad Sobhy', 'Dr. Maged Labib', 'Mr. Boutros Ishaq', 'Eng. George Marcos'],
        'fees_kicker': 'Tuition', 'fees_title': 'A modest investment in a deep journey', 'inside': 'Inside Egypt', 'outside': 'Outside Egypt',
        'egp': 'EGP 850', 'usd': 'USD 75', 'fees_note': 'Fees exclude optional books, study notes, and shipping, which are charged at actual cost.',
        'register_kicker': 'Admissions', 'register_title': 'Four steps to begin',
        'steps': [('Complete the Application', 'Create your account and submit the required information.'), ('Choose Your Track', 'Select on-campus or online study according to your location.'), ('Pay Tuition', 'Via InstaPay, electronic wallet, cash on campus, or bank transfer from abroad.'), ('Account Activation', 'Once registration is complete, access to lectures and materials is activated.')],
        'requirements_title': 'Admission Requirement', 'requirements_text': 'Everyone is invited to study, understand, and go deeper into Scripture through either on-campus or online study.',
        'calendar_title': 'Academic Breaks', 'calendar': [('Mid-year', 'The Christmas and Epiphany period'), ('Easter', 'From the Thursday before the conclusion of Lent through the week after the feast')],
        'faq_kicker': 'FAQ', 'faq_title': 'Quick answers before applying',
        'faq': [('Is online study available to Cairo residents?', 'Under the Institute system, online self-paced study is for other governorates and abroad; Greater Cairo and Giza residents attend on campus.'), ('How do I receive books?', 'Materials are uploaded online. Printed copies can be collected from campus or shipped outside Greater Cairo.'), ('How are exams held?', 'All examinations are online, with windows designed to accommodate students outside Egypt.')],
    },
}


def get_institute_copy(language, page):
    language = 'ar' if language and language.startswith('ar') else 'en'
    pages = {'home': HOME, 'about': ABOUT, 'courses': COURSES}
    return {'copy': {**COMMON[language], **pages[page][language]}, 'language_code': language}
